--chapter - 03

--SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE
--WHERE
--select employee_id , first_name from employees where department_id = 100
--SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Steven'

--SELECT EMPLOYEE_ID , FIRST_NAME , DEPARTMENT_ID FROM EMPLOYEES WHERE SALARY >= 10000 AND DEPARTMENT_ID = 80
-- <> 不等于
--SELECT EMPLOYEE_ID , FIRST_NAME , DEPARTMENT_ID FROM EMPLOYEES WHERE SALARY <> 24000   TO_DATE('' , 'yyyy-MM-dd')
--比较日期
--SELECT EMPLOYEE_ID , FIRST_NAME , HIRE_DATE FROM EMPLOYEES  ORDER BY HIRE_DATE
--SELECT EMPLOYEE_ID , FIRST_NAME , HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE>'17-JUNE-2003' ORDER BY HIRE_DATE
--SELECT EMPLOYEE_ID , FIRST_NAME , HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE>TO_DATE('2003-06-17' , 'yyyy-MM-dd') ORDER BY HIRE_DATE

-- BETWEEN AND
--SELECT EMPLOYEE_ID , FIRST_NAME , SALARY FROM EMPLOYEES WHERE SALARY BETWEEN 10000 AND 20000
--SELECT EMPLOYEE_ID , FIRST_NAME , HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE BETWEEN TO_DATE('2002-01-01' , 'yyyy-MM-dd') AND TO_DATE('2002-12-31' , 'yyyy-MM-dd')

--IN
-- SELECT EMPLOYEE_ID , FIRST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID IN (  90 )
-- --IN 的实际应用
-- SELECT EMPLOYEE_ID , FIRST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID IN (
-- 	SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Executive' OR  DEPARTMENT_NAME = 'IT'
--  )
--

--LIKE
-- SELECT EMPLOYEE_ID , FIRST_NAME FROM EMPLOYEES  WHERE FIRST_NAME LIKE '_s%'

--IS NULL  : 查谁是领导



-- AND
-- SELECT EMPLOYEE_ID , FIRST_NAME FROM EMPLOYEES WHERE FIRST_NAME = 'Steven' AND LAST_NAME = 'King'

--OR
--NOT IN

--优先级
-- SELECT EMPLOYEE_ID , FIRST_NAME , SALARY FROM EMPLOYEES WHERE ( JOB_ID = 'SA_MAN' OR JOB_ID = 'AD_PRES' ) AND SALARY > 13000



--排序
-- SELECT EMPLOYEE_ID , FIRST_NAME , SALARY s FROM EMPLOYEES ORDER BY  s
-- SELECT EMPLOYEE_ID , FIRST_NAME , SALARY , HIRE_DATE FROM EMPLOYEES ORDER BY  SALARY DESC , HIRE_DATE DESC
-- SELECT EMPLOYEE_ID , FIRST_NAME , SALARY , HIRE_DATE FROM EMPLOYEES ORDER BY  3  , 4 DESC
-- SELECT EMPLOYEE_ID , FIRST_NAME  FROM EMPLOYEES ORDER BY  SALARY DESC

--聚合函数 / 分组函数
--SELECT MAX(e.SALARY) , MIN(e.SALARY) , SUM(e.SALARY) , ROUND(AVG(e.SALARY) ,1 ) FROM EMPLOYEES e
-- SELECT COUNT(e.EMPLOYEE_ID) FROM EMPLOYEES e
-- SELECT COUNT(d.DEPARTMENT_ID) FROM DEPARTMENTS d
--ELECT COUNT(*) FROM DEPARTMENTS d

--分组查询
-- SELECT e.DEPARTMENT_ID , ROUND(AVG(e.SALARY) ,1 ) , COUNT(*) , SUM(e.SALARY) FROM EMPLOYEES e
-- GROUP BY e.DEPARTMENT_ID

-- SELECT e.DEPARTMENT_ID , e.JOB_ID , ROUND(AVG(e.SALARY) ,1 ) , COUNT(*) , SUM(e.SALARY) FROM EMPLOYEES e
-- GROUP BY e.DEPARTMENT_ID , e.JOB_ID

-- SELECT e.DEPARTMENT_ID , e.JOB_ID , ROUND(AVG(e.SALARY) ,1 ) S , COUNT(*) , SUM(e.SALARY) FROM EMPLOYEES e
-- GROUP BY e.DEPARTMENT_ID , e.JOB_ID
-- HAVING MAX(e.SALARY) > 15000
-- ORDER BY S DESC
