--创建表
CREATE TABLE <TABLENAME> (
    ID NUMBER PRIMARY KEY NOT NULL ,
    NAME VARCHAR2(100) ,
    EMAIL VARCHAR2(200) DEFAULT 'NOTHING' ,
    ADD DATE
)
--RENAME
ALTER TABLE PERSON RENAME COLUMN OLDNAME TO NEWNAME;
--ADD COLUMN
ALTER TABLE PERSON ADD ( <NAME> <DATETYPE> );
--MODIFY COLUMN
ALTER TABLE PERSON MODIFY  ( <NAME> <DATETYPE> );

--SEQUENCE
CREATE SEQUECE <NAME>;    --> START:1 , INCREMENT:1, END:INFINITY
SELECT SEQ.NEXTVAL FROM DUAL; (FIRST USE , REQUIRED)
SELECT SEQ.CURRVAL FROM DUAL;

--CRUD
--INSERT
INSERT INTO TABLE (ID , NAME , EMAIL) VALUES (SEQ.NEXTVAL , '...' , '....' , SYSDATE )

--UPDATE
UPDATE TABLE SET NAME = ? WHERE COLUMN = ?
--DELETE
DELETE FROM TABLE --> REMOVE ALL
DELETE FROM TABLE WHERE CONDITIONS
